<?php
/**
 * CreateDeepNewsRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AskNews API
 *
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.45
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AskNews\Model;

use \ArrayAccess;
use \AskNews\ObjectSerializer;

/**
 * CreateDeepNewsRequest Class Doc Comment
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateDeepNewsRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateDeepNewsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'messages' => '\AskNews\Model\CreateDeepNewsRequestMessage[]',
        'model' => '\AskNews\Model\CreateDeepNewsRequestModel',
        'filter_params' => '\AskNews\Model\CreateDeepNewsRequestFilterParams',
        'search_depth' => 'int',
        'max_depth' => 'int',
        'sources' => '\AskNews\Model\Sources1',
        'inline_citations' => 'string',
        'start_citation_number' => 'int',
        'return_sources' => 'bool',
        'only_cited_sources' => 'bool',
        'append_references' => 'bool',
        'journalist_mode' => 'bool',
        'conversational_awareness' => 'bool',
        'include_entities' => 'bool',
        'include_graphs' => 'bool',
        'include_coordinates' => 'bool',
        'asknews_watermark' => 'bool',
        'stream' => 'bool',
        'stop' => '\AskNews\Model\Stop1',
        'temperature' => 'float',
        'top_p' => 'float',
        'n' => 'int',
        'max_tokens' => 'int',
        'presence_penalty' => 'int',
        'frequency_penalty' => 'int',
        'user' => '\AskNews\Model\User1',
        'thread_id' => '\AskNews\Model\ThreadId1'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'messages' => null,
        'model' => null,
        'filter_params' => null,
        'search_depth' => null,
        'max_depth' => null,
        'sources' => null,
        'inline_citations' => null,
        'start_citation_number' => null,
        'return_sources' => null,
        'only_cited_sources' => null,
        'append_references' => null,
        'journalist_mode' => null,
        'conversational_awareness' => null,
        'include_entities' => null,
        'include_graphs' => null,
        'include_coordinates' => null,
        'asknews_watermark' => null,
        'stream' => null,
        'stop' => null,
        'temperature' => null,
        'top_p' => null,
        'n' => null,
        'max_tokens' => null,
        'presence_penalty' => null,
        'frequency_penalty' => null,
        'user' => null,
        'thread_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'messages' => false,
        'model' => false,
        'filter_params' => false,
        'search_depth' => false,
        'max_depth' => false,
        'sources' => false,
        'inline_citations' => false,
        'start_citation_number' => false,
        'return_sources' => false,
        'only_cited_sources' => false,
        'append_references' => false,
        'journalist_mode' => false,
        'conversational_awareness' => false,
        'include_entities' => false,
        'include_graphs' => false,
        'include_coordinates' => false,
        'asknews_watermark' => false,
        'stream' => false,
        'stop' => false,
        'temperature' => false,
        'top_p' => false,
        'n' => false,
        'max_tokens' => false,
        'presence_penalty' => false,
        'frequency_penalty' => false,
        'user' => false,
        'thread_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'messages' => 'messages',
        'model' => 'model',
        'filter_params' => 'filter_params',
        'search_depth' => 'search_depth',
        'max_depth' => 'max_depth',
        'sources' => 'sources',
        'inline_citations' => 'inline_citations',
        'start_citation_number' => 'start_citation_number',
        'return_sources' => 'return_sources',
        'only_cited_sources' => 'only_cited_sources',
        'append_references' => 'append_references',
        'journalist_mode' => 'journalist_mode',
        'conversational_awareness' => 'conversational_awareness',
        'include_entities' => 'include_entities',
        'include_graphs' => 'include_graphs',
        'include_coordinates' => 'include_coordinates',
        'asknews_watermark' => 'asknews_watermark',
        'stream' => 'stream',
        'stop' => 'stop',
        'temperature' => 'temperature',
        'top_p' => 'top_p',
        'n' => 'n',
        'max_tokens' => 'max_tokens',
        'presence_penalty' => 'presence_penalty',
        'frequency_penalty' => 'frequency_penalty',
        'user' => 'user',
        'thread_id' => 'thread_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'messages' => 'setMessages',
        'model' => 'setModel',
        'filter_params' => 'setFilterParams',
        'search_depth' => 'setSearchDepth',
        'max_depth' => 'setMaxDepth',
        'sources' => 'setSources',
        'inline_citations' => 'setInlineCitations',
        'start_citation_number' => 'setStartCitationNumber',
        'return_sources' => 'setReturnSources',
        'only_cited_sources' => 'setOnlyCitedSources',
        'append_references' => 'setAppendReferences',
        'journalist_mode' => 'setJournalistMode',
        'conversational_awareness' => 'setConversationalAwareness',
        'include_entities' => 'setIncludeEntities',
        'include_graphs' => 'setIncludeGraphs',
        'include_coordinates' => 'setIncludeCoordinates',
        'asknews_watermark' => 'setAsknewsWatermark',
        'stream' => 'setStream',
        'stop' => 'setStop',
        'temperature' => 'setTemperature',
        'top_p' => 'setTopP',
        'n' => 'setN',
        'max_tokens' => 'setMaxTokens',
        'presence_penalty' => 'setPresencePenalty',
        'frequency_penalty' => 'setFrequencyPenalty',
        'user' => 'setUser',
        'thread_id' => 'setThreadId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'messages' => 'getMessages',
        'model' => 'getModel',
        'filter_params' => 'getFilterParams',
        'search_depth' => 'getSearchDepth',
        'max_depth' => 'getMaxDepth',
        'sources' => 'getSources',
        'inline_citations' => 'getInlineCitations',
        'start_citation_number' => 'getStartCitationNumber',
        'return_sources' => 'getReturnSources',
        'only_cited_sources' => 'getOnlyCitedSources',
        'append_references' => 'getAppendReferences',
        'journalist_mode' => 'getJournalistMode',
        'conversational_awareness' => 'getConversationalAwareness',
        'include_entities' => 'getIncludeEntities',
        'include_graphs' => 'getIncludeGraphs',
        'include_coordinates' => 'getIncludeCoordinates',
        'asknews_watermark' => 'getAsknewsWatermark',
        'stream' => 'getStream',
        'stop' => 'getStop',
        'temperature' => 'getTemperature',
        'top_p' => 'getTopP',
        'n' => 'getN',
        'max_tokens' => 'getMaxTokens',
        'presence_penalty' => 'getPresencePenalty',
        'frequency_penalty' => 'getFrequencyPenalty',
        'user' => 'getUser',
        'thread_id' => 'getThreadId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const INLINE_CITATIONS_MARKDOWN_LINK = 'markdown_link';
    public const INLINE_CITATIONS_NUMBERED = 'numbered';
    public const INLINE_CITATIONS_NONE = 'none';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getInlineCitationsAllowableValues()
    {
        return [
            self::INLINE_CITATIONS_MARKDOWN_LINK,
            self::INLINE_CITATIONS_NUMBERED,
            self::INLINE_CITATIONS_NONE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('messages', $data ?? [], null);
        $this->setIfExists('model', $data ?? [], null);
        $this->setIfExists('filter_params', $data ?? [], null);
        $this->setIfExists('search_depth', $data ?? [], 2);
        $this->setIfExists('max_depth', $data ?? [], 6);
        $this->setIfExists('sources', $data ?? [], null);
        $this->setIfExists('inline_citations', $data ?? [], 'markdown_link');
        $this->setIfExists('start_citation_number', $data ?? [], 1);
        $this->setIfExists('return_sources', $data ?? [], true);
        $this->setIfExists('only_cited_sources', $data ?? [], true);
        $this->setIfExists('append_references', $data ?? [], true);
        $this->setIfExists('journalist_mode', $data ?? [], true);
        $this->setIfExists('conversational_awareness', $data ?? [], true);
        $this->setIfExists('include_entities', $data ?? [], true);
        $this->setIfExists('include_graphs', $data ?? [], false);
        $this->setIfExists('include_coordinates', $data ?? [], false);
        $this->setIfExists('asknews_watermark', $data ?? [], true);
        $this->setIfExists('stream', $data ?? [], false);
        $this->setIfExists('stop', $data ?? [], null);
        $this->setIfExists('temperature', $data ?? [], 0.9);
        $this->setIfExists('top_p', $data ?? [], 1.0);
        $this->setIfExists('n', $data ?? [], 1);
        $this->setIfExists('max_tokens', $data ?? [], 9999);
        $this->setIfExists('presence_penalty', $data ?? [], 0);
        $this->setIfExists('frequency_penalty', $data ?? [], 0);
        $this->setIfExists('user', $data ?? [], null);
        $this->setIfExists('thread_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['messages'] === null) {
            $invalidProperties[] = "'messages' can't be null";
        }
        if (!is_null($this->container['search_depth']) && ($this->container['search_depth'] > 60)) {
            $invalidProperties[] = "invalid value for 'search_depth', must be smaller than or equal to 60.";
        }

        if (!is_null($this->container['search_depth']) && ($this->container['search_depth'] < 1)) {
            $invalidProperties[] = "invalid value for 'search_depth', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['max_depth']) && ($this->container['max_depth'] > 100)) {
            $invalidProperties[] = "invalid value for 'max_depth', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['max_depth']) && ($this->container['max_depth'] < 1)) {
            $invalidProperties[] = "invalid value for 'max_depth', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getInlineCitationsAllowableValues();
        if (!is_null($this->container['inline_citations']) && !in_array($this->container['inline_citations'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'inline_citations', must be one of '%s'",
                $this->container['inline_citations'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets messages
     *
     * @return \AskNews\Model\CreateDeepNewsRequestMessage[]
     */
    public function getMessages()
    {
        return $this->container['messages'];
    }

    /**
     * Sets messages
     *
     * @param \AskNews\Model\CreateDeepNewsRequestMessage[] $messages The messages to send to DeepNews. Each message should have 'role' and 'content' keys. Use this to specify what research/monitoring task DeepNews should perform. The 'content' for the final 'user' message should be your Alert query.
     *
     * @return self
     */
    public function setMessages($messages)
    {
        if (is_null($messages)) {
            throw new \InvalidArgumentException('non-nullable messages cannot be null');
        }
        $this->container['messages'] = $messages;

        return $this;
    }

    /**
     * Gets model
     *
     * @return \AskNews\Model\CreateDeepNewsRequestModel|null
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param \AskNews\Model\CreateDeepNewsRequestModel|null $model model
     *
     * @return self
     */
    public function setModel($model)
    {
        if (is_null($model)) {
            throw new \InvalidArgumentException('non-nullable model cannot be null');
        }
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets filter_params
     *
     * @return \AskNews\Model\CreateDeepNewsRequestFilterParams|null
     */
    public function getFilterParams()
    {
        return $this->container['filter_params'];
    }

    /**
     * Sets filter_params
     *
     * @param \AskNews\Model\CreateDeepNewsRequestFilterParams|null $filter_params filter_params
     *
     * @return self
     */
    public function setFilterParams($filter_params)
    {
        if (is_null($filter_params)) {
            throw new \InvalidArgumentException('non-nullable filter_params cannot be null');
        }
        $this->container['filter_params'] = $filter_params;

        return $this;
    }

    /**
     * Gets search_depth
     *
     * @return int|null
     */
    public function getSearchDepth()
    {
        return $this->container['search_depth'];
    }

    /**
     * Sets search_depth
     *
     * @param int|null $search_depth The search depth for deep research. Higher values mean more thorough research.
     *
     * @return self
     */
    public function setSearchDepth($search_depth)
    {
        if (is_null($search_depth)) {
            throw new \InvalidArgumentException('non-nullable search_depth cannot be null');
        }

        if (($search_depth > 60)) {
            throw new \InvalidArgumentException('invalid value for $search_depth when calling CreateDeepNewsRequest., must be smaller than or equal to 60.');
        }
        if (($search_depth < 1)) {
            throw new \InvalidArgumentException('invalid value for $search_depth when calling CreateDeepNewsRequest., must be bigger than or equal to 1.');
        }

        $this->container['search_depth'] = $search_depth;

        return $this;
    }

    /**
     * Gets max_depth
     *
     * @return int|null
     */
    public function getMaxDepth()
    {
        return $this->container['max_depth'];
    }

    /**
     * Sets max_depth
     *
     * @param int|null $max_depth The maximum research depth allowed.
     *
     * @return self
     */
    public function setMaxDepth($max_depth)
    {
        if (is_null($max_depth)) {
            throw new \InvalidArgumentException('non-nullable max_depth cannot be null');
        }

        if (($max_depth > 100)) {
            throw new \InvalidArgumentException('invalid value for $max_depth when calling CreateDeepNewsRequest., must be smaller than or equal to 100.');
        }
        if (($max_depth < 1)) {
            throw new \InvalidArgumentException('invalid value for $max_depth when calling CreateDeepNewsRequest., must be bigger than or equal to 1.');
        }

        $this->container['max_depth'] = $max_depth;

        return $this;
    }

    /**
     * Gets sources
     *
     * @return \AskNews\Model\Sources1|null
     */
    public function getSources()
    {
        return $this->container['sources'];
    }

    /**
     * Sets sources
     *
     * @param \AskNews\Model\Sources1|null $sources sources
     *
     * @return self
     */
    public function setSources($sources)
    {
        if (is_null($sources)) {
            throw new \InvalidArgumentException('non-nullable sources cannot be null');
        }
        $this->container['sources'] = $sources;

        return $this;
    }

    /**
     * Gets inline_citations
     *
     * @return string|null
     */
    public function getInlineCitations()
    {
        return $this->container['inline_citations'];
    }

    /**
     * Sets inline_citations
     *
     * @param string|null $inline_citations How to format inline citations in the response. Defaults to: markdown_link. Available options: markdown_link, numbered, none
     *
     * @return self
     */
    public function setInlineCitations($inline_citations)
    {
        if (is_null($inline_citations)) {
            throw new \InvalidArgumentException('non-nullable inline_citations cannot be null');
        }
        $allowedValues = $this->getInlineCitationsAllowableValues();
        if (!in_array($inline_citations, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'inline_citations', must be one of '%s'",
                    $inline_citations,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['inline_citations'] = $inline_citations;

        return $this;
    }

    /**
     * Gets start_citation_number
     *
     * @return int|null
     */
    public function getStartCitationNumber()
    {
        return $this->container['start_citation_number'];
    }

    /**
     * Sets start_citation_number
     *
     * @param int|null $start_citation_number Starting number for inline citations. Offsets fetched source citation keys. Useful if you are providing the agent outside sources with numbered citation keys.
     *
     * @return self
     */
    public function setStartCitationNumber($start_citation_number)
    {
        if (is_null($start_citation_number)) {
            throw new \InvalidArgumentException('non-nullable start_citation_number cannot be null');
        }
        $this->container['start_citation_number'] = $start_citation_number;

        return $this;
    }

    /**
     * Gets return_sources
     *
     * @return bool|null
     */
    public function getReturnSources()
    {
        return $this->container['return_sources'];
    }

    /**
     * Sets return_sources
     *
     * @param bool|null $return_sources Whether return a list of sources used by the agent.
     *
     * @return self
     */
    public function setReturnSources($return_sources)
    {
        if (is_null($return_sources)) {
            throw new \InvalidArgumentException('non-nullable return_sources cannot be null');
        }
        $this->container['return_sources'] = $return_sources;

        return $this;
    }

    /**
     * Gets only_cited_sources
     *
     * @return bool|null
     */
    public function getOnlyCitedSources()
    {
        return $this->container['only_cited_sources'];
    }

    /**
     * Sets only_cited_sources
     *
     * @param bool|null $only_cited_sources Whether to return only of sources that are cited/referenced in the generated response content.
     *
     * @return self
     */
    public function setOnlyCitedSources($only_cited_sources)
    {
        if (is_null($only_cited_sources)) {
            throw new \InvalidArgumentException('non-nullable only_cited_sources cannot be null');
        }
        $this->container['only_cited_sources'] = $only_cited_sources;

        return $this;
    }

    /**
     * Gets append_references
     *
     * @return bool|null
     */
    public function getAppendReferences()
    {
        return $this->container['append_references'];
    }

    /**
     * Sets append_references
     *
     * @param bool|null $append_references Whether to append a 'Cited Articles' section at the end of the response.
     *
     * @return self
     */
    public function setAppendReferences($append_references)
    {
        if (is_null($append_references)) {
            throw new \InvalidArgumentException('non-nullable append_references cannot be null');
        }
        $this->container['append_references'] = $append_references;

        return $this;
    }

    /**
     * Gets journalist_mode
     *
     * @return bool|null
     */
    public function getJournalistMode()
    {
        return $this->container['journalist_mode'];
    }

    /**
     * Sets journalist_mode
     *
     * @param bool|null $journalist_mode Whether to use journalist mode for more factual reporting.
     *
     * @return self
     */
    public function setJournalistMode($journalist_mode)
    {
        if (is_null($journalist_mode)) {
            throw new \InvalidArgumentException('non-nullable journalist_mode cannot be null');
        }
        $this->container['journalist_mode'] = $journalist_mode;

        return $this;
    }

    /**
     * Gets conversational_awareness
     *
     * @return bool|null
     */
    public function getConversationalAwareness()
    {
        return $this->container['conversational_awareness'];
    }

    /**
     * Sets conversational_awareness
     *
     * @param bool|null $conversational_awareness Whether to use conversational awareness.
     *
     * @return self
     */
    public function setConversationalAwareness($conversational_awareness)
    {
        if (is_null($conversational_awareness)) {
            throw new \InvalidArgumentException('non-nullable conversational_awareness cannot be null');
        }
        $this->container['conversational_awareness'] = $conversational_awareness;

        return $this;
    }

    /**
     * Gets include_entities
     *
     * @return bool|null
     */
    public function getIncludeEntities()
    {
        return $this->container['include_entities'];
    }

    /**
     * Sets include_entities
     *
     * @param bool|null $include_entities Whether to provide extracted entities to the agent.
     *
     * @return self
     */
    public function setIncludeEntities($include_entities)
    {
        if (is_null($include_entities)) {
            throw new \InvalidArgumentException('non-nullable include_entities cannot be null');
        }
        $this->container['include_entities'] = $include_entities;

        return $this;
    }

    /**
     * Gets include_graphs
     *
     * @return bool|null
     */
    public function getIncludeGraphs()
    {
        return $this->container['include_graphs'];
    }

    /**
     * Sets include_graphs
     *
     * @param bool|null $include_graphs Whether to provide knowledge graphs to the agent
     *
     * @return self
     */
    public function setIncludeGraphs($include_graphs)
    {
        if (is_null($include_graphs)) {
            throw new \InvalidArgumentException('non-nullable include_graphs cannot be null');
        }
        $this->container['include_graphs'] = $include_graphs;

        return $this;
    }

    /**
     * Gets include_coordinates
     *
     * @return bool|null
     */
    public function getIncludeCoordinates()
    {
        return $this->container['include_coordinates'];
    }

    /**
     * Sets include_coordinates
     *
     * @param bool|null $include_coordinates Whether to provide geo coordinates to the agent.
     *
     * @return self
     */
    public function setIncludeCoordinates($include_coordinates)
    {
        if (is_null($include_coordinates)) {
            throw new \InvalidArgumentException('non-nullable include_coordinates cannot be null');
        }
        $this->container['include_coordinates'] = $include_coordinates;

        return $this;
    }

    /**
     * Gets asknews_watermark
     *
     * @return bool|null
     */
    public function getAsknewsWatermark()
    {
        return $this->container['asknews_watermark'];
    }

    /**
     * Sets asknews_watermark
     *
     * @param bool|null $asknews_watermark Append 'Generated by AskNews AI' watermark
     *
     * @return self
     */
    public function setAsknewsWatermark($asknews_watermark)
    {
        if (is_null($asknews_watermark)) {
            throw new \InvalidArgumentException('non-nullable asknews_watermark cannot be null');
        }
        $this->container['asknews_watermark'] = $asknews_watermark;

        return $this;
    }

    /**
     * Gets stream
     *
     * @return bool|null
     */
    public function getStream()
    {
        return $this->container['stream'];
    }

    /**
     * Sets stream
     *
     * @param bool|null $stream Whether to stream the response as server-sent events.
     *
     * @return self
     */
    public function setStream($stream)
    {
        if (is_null($stream)) {
            throw new \InvalidArgumentException('non-nullable stream cannot be null');
        }
        $this->container['stream'] = $stream;

        return $this;
    }

    /**
     * Gets stop
     *
     * @return \AskNews\Model\Stop1|null
     */
    public function getStop()
    {
        return $this->container['stop'];
    }

    /**
     * Sets stop
     *
     * @param \AskNews\Model\Stop1|null $stop stop
     *
     * @return self
     */
    public function setStop($stop)
    {
        if (is_null($stop)) {
            throw new \InvalidArgumentException('non-nullable stop cannot be null');
        }
        $this->container['stop'] = $stop;

        return $this;
    }

    /**
     * Gets temperature
     *
     * @return float|null
     */
    public function getTemperature()
    {
        return $this->container['temperature'];
    }

    /**
     * Sets temperature
     *
     * @param float|null $temperature The temperature of the DeepNews agent model. Controls randomness in the output. Higher values (e.g., 1.0) make output more random, lower values (e.g., 0.1) make it more deterministic.
     *
     * @return self
     */
    public function setTemperature($temperature)
    {
        if (is_null($temperature)) {
            throw new \InvalidArgumentException('non-nullable temperature cannot be null');
        }
        $this->container['temperature'] = $temperature;

        return $this;
    }

    /**
     * Gets top_p
     *
     * @return float|null
     */
    public function getTopP()
    {
        return $this->container['top_p'];
    }

    /**
     * Sets top_p
     *
     * @param float|null $top_p Nucleus sampling parameter. Only tokens with cumulative probability up to top_p are considered.
     *
     * @return self
     */
    public function setTopP($top_p)
    {
        if (is_null($top_p)) {
            throw new \InvalidArgumentException('non-nullable top_p cannot be null');
        }
        $this->container['top_p'] = $top_p;

        return $this;
    }

    /**
     * Gets n
     *
     * @return int|null
     */
    public function getN()
    {
        return $this->container['n'];
    }

    /**
     * Sets n
     *
     * @param int|null $n Number of completions to generate.
     *
     * @return self
     */
    public function setN($n)
    {
        if (is_null($n)) {
            throw new \InvalidArgumentException('non-nullable n cannot be null');
        }
        $this->container['n'] = $n;

        return $this;
    }

    /**
     * Gets max_tokens
     *
     * @return int|null
     */
    public function getMaxTokens()
    {
        return $this->container['max_tokens'];
    }

    /**
     * Sets max_tokens
     *
     * @param int|null $max_tokens Maximum number of tokens to generate in the response.
     *
     * @return self
     */
    public function setMaxTokens($max_tokens)
    {
        if (is_null($max_tokens)) {
            throw new \InvalidArgumentException('non-nullable max_tokens cannot be null');
        }
        $this->container['max_tokens'] = $max_tokens;

        return $this;
    }

    /**
     * Gets presence_penalty
     *
     * @return int|null
     */
    public function getPresencePenalty()
    {
        return $this->container['presence_penalty'];
    }

    /**
     * Sets presence_penalty
     *
     * @param int|null $presence_penalty Penalizes new tokens based on whether they appear in the text so far, encouraging new topics.
     *
     * @return self
     */
    public function setPresencePenalty($presence_penalty)
    {
        if (is_null($presence_penalty)) {
            throw new \InvalidArgumentException('non-nullable presence_penalty cannot be null');
        }
        $this->container['presence_penalty'] = $presence_penalty;

        return $this;
    }

    /**
     * Gets frequency_penalty
     *
     * @return int|null
     */
    public function getFrequencyPenalty()
    {
        return $this->container['frequency_penalty'];
    }

    /**
     * Sets frequency_penalty
     *
     * @param int|null $frequency_penalty Penalizes new tokens based on their frequency in the text so far, reducing repetition.
     *
     * @return self
     */
    public function setFrequencyPenalty($frequency_penalty)
    {
        if (is_null($frequency_penalty)) {
            throw new \InvalidArgumentException('non-nullable frequency_penalty cannot be null');
        }
        $this->container['frequency_penalty'] = $frequency_penalty;

        return $this;
    }

    /**
     * Gets user
     *
     * @return \AskNews\Model\User1|null
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param \AskNews\Model\User1|null $user user
     *
     * @return self
     */
    public function setUser($user)
    {
        if (is_null($user)) {
            throw new \InvalidArgumentException('non-nullable user cannot be null');
        }
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets thread_id
     *
     * @return \AskNews\Model\ThreadId1|null
     */
    public function getThreadId()
    {
        return $this->container['thread_id'];
    }

    /**
     * Sets thread_id
     *
     * @param \AskNews\Model\ThreadId1|null $thread_id thread_id
     *
     * @return self
     */
    public function setThreadId($thread_id)
    {
        if (is_null($thread_id)) {
            throw new \InvalidArgumentException('non-nullable thread_id cannot be null');
        }
        $this->container['thread_id'] = $thread_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


