<?php
/**
 * DeepNewsModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AskNews API
 *
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.51
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AskNews\Model;
use \AskNews\ObjectSerializer;

/**
 * DeepNewsModel Class Doc Comment
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeepNewsModel
{
    /**
     * Possible values of this enum
     */
    public const O1_MINI = 'o1-mini';

    public const O1 = 'o1';

    public const O3_MINI = 'o3-mini';

    public const O3 = 'o3';

    public const GPT_4O_MINI = 'gpt-4o-mini';

    public const GPT_4O = 'gpt-4o';

    public const GPT_4_1_2025_04_14 = 'gpt-4.1-2025-04-14';

    public const GPT_5_MINI = 'gpt-5-mini';

    public const GPT_5 = 'gpt-5';

    public const COMMAND_NIGHTLY = 'command-nightly';

    public const CLAUDE_3_5_SONNET_20240620 = 'claude-3-5-sonnet-20240620';

    public const CLAUDE_3_5_SONNET_LATEST = 'claude-3-5-sonnet-latest';

    public const CLAUDE_3_7_SONNET_LATEST = 'claude-3-7-sonnet-latest';

    public const CLAUDE_3_7_SONNET_20250219 = 'claude-3-7-sonnet-20250219';

    public const CLAUDE_3_7_SONNET_NOTHINKING = 'claude-3-7-sonnet-nothinking';

    public const CLAUDE_SONNET_4_20250514 = 'claude-sonnet-4-20250514';

    public const CLAUDE_OPUS_4_20250514 = 'claude-opus-4-20250514';

    public const CLAUDE_SONNET_4_5_20250929 = 'claude-sonnet-4-5-20250929';

    public const CLAUDE_OPUS_4_5_20251101 = 'claude-opus-4-5-20251101';

    public const CLAUDE_SONNET_4_6 = 'claude-sonnet-4-6';

    public const CLAUDE_OPUS_4_6 = 'claude-opus-4-6';

    public const DEEPSEEK = 'deepseek';

    public const DEEPSEEK_BASIC = 'deepseek-basic';

    public const DEEPSEEK_R1_0528 = 'deepseek-r1-0528';

    public const META_LLAMA_META_LLAMA_3_8_B_INSTRUCT = 'meta-llama/Meta-Llama-3-8B-Instruct';

    public const META_LLAMA_META_LLAMA_3_1_405_B_INSTRUCT = 'meta-llama/Meta-Llama-3.1-405B-Instruct';

    public const META_LLAMA_META_LLAMA_3_3_70_B_INSTRUCT = 'meta-llama/Meta-Llama-3.3-70B-Instruct';

    public const META_LLAMA_LLAMA_4_MAVERICK_17_B_128_E_INSTRUCT = 'meta-llama/Llama-4-Maverick-17B-128E-Instruct';

    public const GEMINI_2_5_FLASH = 'gemini-2.5-flash';

    public const GEMINI_2_5_PRO = 'gemini-2.5-pro';

    public const GEMINI_2_5_PRO_PREVIEW_03_25 = 'gemini-2.5-pro-preview-03-25';

    public const GEMINI_3_PRO = 'gemini-3-pro';

    public const GEMINI_3_1_PRO = 'gemini-3.1-pro';

    public const GEMINI_3_FLASH = 'gemini-3-flash';

    public const OPEN_SOURCE_BEST = 'open-source-best';

    public const KIMI_K2P5 = 'kimi-k2p5';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::O1_MINI,
            self::O1,
            self::O3_MINI,
            self::O3,
            self::GPT_4O_MINI,
            self::GPT_4O,
            self::GPT_4_1_2025_04_14,
            self::GPT_5_MINI,
            self::GPT_5,
            self::COMMAND_NIGHTLY,
            self::CLAUDE_3_5_SONNET_20240620,
            self::CLAUDE_3_5_SONNET_LATEST,
            self::CLAUDE_3_7_SONNET_LATEST,
            self::CLAUDE_3_7_SONNET_20250219,
            self::CLAUDE_3_7_SONNET_NOTHINKING,
            self::CLAUDE_SONNET_4_20250514,
            self::CLAUDE_OPUS_4_20250514,
            self::CLAUDE_SONNET_4_5_20250929,
            self::CLAUDE_OPUS_4_5_20251101,
            self::CLAUDE_SONNET_4_6,
            self::CLAUDE_OPUS_4_6,
            self::DEEPSEEK,
            self::DEEPSEEK_BASIC,
            self::DEEPSEEK_R1_0528,
            self::META_LLAMA_META_LLAMA_3_8_B_INSTRUCT,
            self::META_LLAMA_META_LLAMA_3_1_405_B_INSTRUCT,
            self::META_LLAMA_META_LLAMA_3_3_70_B_INSTRUCT,
            self::META_LLAMA_LLAMA_4_MAVERICK_17_B_128_E_INSTRUCT,
            self::GEMINI_2_5_FLASH,
            self::GEMINI_2_5_PRO,
            self::GEMINI_2_5_PRO_PREVIEW_03_25,
            self::GEMINI_3_PRO,
            self::GEMINI_3_1_PRO,
            self::GEMINI_3_FLASH,
            self::OPEN_SOURCE_BEST,
            self::KIMI_K2P5
        ];
    }
}


