<?php
/**
 * SeriesConfig
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AskNews API
 *
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.22
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AskNews\Model;

use \ArrayAccess;
use \AskNews\ObjectSerializer;

/**
 * SeriesConfig Class Doc Comment
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SeriesConfig implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SeriesConfig';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'start_datetime' => '\DateTime',
        'end_datetime' => '\DateTime',
        'sampling' => 'string',
        'time_filter' => 'string',
        'categories' => 'string[]',
        'domains' => 'string[]',
        'bad_domain_url' => 'string[]',
        'page_rank' => 'int',
        'string_guarantee' => 'string[]',
        'string_guarantee_op' => 'string',
        'reverse_string_guarantee' => 'string[]',
        'entity_guarantee' => 'string[]',
        'entity_guarantee_op' => 'string',
        'countries' => 'string[]',
        'countries_blacklist' => 'string[]',
        'continents' => 'string[]',
        'languages' => 'string[]',
        'sentiment' => 'string',
        'reporting_voice' => 'string[]',
        'provocative' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'start_datetime' => 'date-time',
        'end_datetime' => 'date-time',
        'sampling' => null,
        'time_filter' => null,
        'categories' => null,
        'domains' => null,
        'bad_domain_url' => null,
        'page_rank' => null,
        'string_guarantee' => null,
        'string_guarantee_op' => null,
        'reverse_string_guarantee' => null,
        'entity_guarantee' => null,
        'entity_guarantee_op' => null,
        'countries' => null,
        'countries_blacklist' => null,
        'continents' => null,
        'languages' => null,
        'sentiment' => null,
        'reporting_voice' => null,
        'provocative' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'start_datetime' => false,
        'end_datetime' => false,
        'sampling' => true,
        'time_filter' => true,
        'categories' => true,
        'domains' => true,
        'bad_domain_url' => true,
        'page_rank' => true,
        'string_guarantee' => true,
        'string_guarantee_op' => true,
        'reverse_string_guarantee' => true,
        'entity_guarantee' => true,
        'entity_guarantee_op' => true,
        'countries' => true,
        'countries_blacklist' => true,
        'continents' => true,
        'languages' => true,
        'sentiment' => true,
        'reporting_voice' => true,
        'provocative' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'start_datetime' => 'start_datetime',
        'end_datetime' => 'end_datetime',
        'sampling' => 'sampling',
        'time_filter' => 'time_filter',
        'categories' => 'categories',
        'domains' => 'domains',
        'bad_domain_url' => 'bad_domain_url',
        'page_rank' => 'page_rank',
        'string_guarantee' => 'string_guarantee',
        'string_guarantee_op' => 'string_guarantee_op',
        'reverse_string_guarantee' => 'reverse_string_guarantee',
        'entity_guarantee' => 'entity_guarantee',
        'entity_guarantee_op' => 'entity_guarantee_op',
        'countries' => 'countries',
        'countries_blacklist' => 'countries_blacklist',
        'continents' => 'continents',
        'languages' => 'languages',
        'sentiment' => 'sentiment',
        'reporting_voice' => 'reporting_voice',
        'provocative' => 'provocative'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'start_datetime' => 'setStartDatetime',
        'end_datetime' => 'setEndDatetime',
        'sampling' => 'setSampling',
        'time_filter' => 'setTimeFilter',
        'categories' => 'setCategories',
        'domains' => 'setDomains',
        'bad_domain_url' => 'setBadDomainUrl',
        'page_rank' => 'setPageRank',
        'string_guarantee' => 'setStringGuarantee',
        'string_guarantee_op' => 'setStringGuaranteeOp',
        'reverse_string_guarantee' => 'setReverseStringGuarantee',
        'entity_guarantee' => 'setEntityGuarantee',
        'entity_guarantee_op' => 'setEntityGuaranteeOp',
        'countries' => 'setCountries',
        'countries_blacklist' => 'setCountriesBlacklist',
        'continents' => 'setContinents',
        'languages' => 'setLanguages',
        'sentiment' => 'setSentiment',
        'reporting_voice' => 'setReportingVoice',
        'provocative' => 'setProvocative'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'start_datetime' => 'getStartDatetime',
        'end_datetime' => 'getEndDatetime',
        'sampling' => 'getSampling',
        'time_filter' => 'getTimeFilter',
        'categories' => 'getCategories',
        'domains' => 'getDomains',
        'bad_domain_url' => 'getBadDomainUrl',
        'page_rank' => 'getPageRank',
        'string_guarantee' => 'getStringGuarantee',
        'string_guarantee_op' => 'getStringGuaranteeOp',
        'reverse_string_guarantee' => 'getReverseStringGuarantee',
        'entity_guarantee' => 'getEntityGuarantee',
        'entity_guarantee_op' => 'getEntityGuaranteeOp',
        'countries' => 'getCountries',
        'countries_blacklist' => 'getCountriesBlacklist',
        'continents' => 'getContinents',
        'languages' => 'getLanguages',
        'sentiment' => 'getSentiment',
        'reporting_voice' => 'getReportingVoice',
        'provocative' => 'getProvocative'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('start_datetime', $data ?? [], null);
        $this->setIfExists('end_datetime', $data ?? [], null);
        $this->setIfExists('sampling', $data ?? [], null);
        $this->setIfExists('time_filter', $data ?? [], null);
        $this->setIfExists('categories', $data ?? [], null);
        $this->setIfExists('domains', $data ?? [], null);
        $this->setIfExists('bad_domain_url', $data ?? [], null);
        $this->setIfExists('page_rank', $data ?? [], null);
        $this->setIfExists('string_guarantee', $data ?? [], null);
        $this->setIfExists('string_guarantee_op', $data ?? [], null);
        $this->setIfExists('reverse_string_guarantee', $data ?? [], null);
        $this->setIfExists('entity_guarantee', $data ?? [], null);
        $this->setIfExists('entity_guarantee_op', $data ?? [], null);
        $this->setIfExists('countries', $data ?? [], null);
        $this->setIfExists('countries_blacklist', $data ?? [], null);
        $this->setIfExists('continents', $data ?? [], null);
        $this->setIfExists('languages', $data ?? [], null);
        $this->setIfExists('sentiment', $data ?? [], null);
        $this->setIfExists('reporting_voice', $data ?? [], null);
        $this->setIfExists('provocative', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['start_datetime'] === null) {
            $invalidProperties[] = "'start_datetime' can't be null";
        }
        if ($this->container['end_datetime'] === null) {
            $invalidProperties[] = "'end_datetime' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets start_datetime
     *
     * @return \DateTime
     */
    public function getStartDatetime()
    {
        return $this->container['start_datetime'];
    }

    /**
     * Sets start_datetime
     *
     * @param \DateTime $start_datetime start_datetime
     *
     * @return self
     */
    public function setStartDatetime($start_datetime)
    {
        if (is_null($start_datetime)) {
            throw new \InvalidArgumentException('non-nullable start_datetime cannot be null');
        }
        $this->container['start_datetime'] = $start_datetime;

        return $this;
    }

    /**
     * Gets end_datetime
     *
     * @return \DateTime
     */
    public function getEndDatetime()
    {
        return $this->container['end_datetime'];
    }

    /**
     * Sets end_datetime
     *
     * @param \DateTime $end_datetime end_datetime
     *
     * @return self
     */
    public function setEndDatetime($end_datetime)
    {
        if (is_null($end_datetime)) {
            throw new \InvalidArgumentException('non-nullable end_datetime cannot be null');
        }
        $this->container['end_datetime'] = $end_datetime;

        return $this;
    }

    /**
     * Gets sampling
     *
     * @return string|null
     */
    public function getSampling()
    {
        return $this->container['sampling'];
    }

    /**
     * Sets sampling
     *
     * @param string|null $sampling sampling
     *
     * @return self
     */
    public function setSampling($sampling)
    {
        if (is_null($sampling)) {
            array_push($this->openAPINullablesSetToNull, 'sampling');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sampling', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sampling'] = $sampling;

        return $this;
    }

    /**
     * Gets time_filter
     *
     * @return string|null
     */
    public function getTimeFilter()
    {
        return $this->container['time_filter'];
    }

    /**
     * Sets time_filter
     *
     * @param string|null $time_filter time_filter
     *
     * @return self
     */
    public function setTimeFilter($time_filter)
    {
        if (is_null($time_filter)) {
            array_push($this->openAPINullablesSetToNull, 'time_filter');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('time_filter', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['time_filter'] = $time_filter;

        return $this;
    }

    /**
     * Gets categories
     *
     * @return string[]|null
     */
    public function getCategories()
    {
        return $this->container['categories'];
    }

    /**
     * Sets categories
     *
     * @param string[]|null $categories categories
     *
     * @return self
     */
    public function setCategories($categories)
    {
        if (is_null($categories)) {
            array_push($this->openAPINullablesSetToNull, 'categories');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('categories', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['categories'] = $categories;

        return $this;
    }

    /**
     * Gets domains
     *
     * @return string[]|null
     */
    public function getDomains()
    {
        return $this->container['domains'];
    }

    /**
     * Sets domains
     *
     * @param string[]|null $domains domains
     *
     * @return self
     */
    public function setDomains($domains)
    {
        if (is_null($domains)) {
            array_push($this->openAPINullablesSetToNull, 'domains');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domains', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domains'] = $domains;

        return $this;
    }

    /**
     * Gets bad_domain_url
     *
     * @return string[]|null
     */
    public function getBadDomainUrl()
    {
        return $this->container['bad_domain_url'];
    }

    /**
     * Sets bad_domain_url
     *
     * @param string[]|null $bad_domain_url bad_domain_url
     *
     * @return self
     */
    public function setBadDomainUrl($bad_domain_url)
    {
        if (is_null($bad_domain_url)) {
            array_push($this->openAPINullablesSetToNull, 'bad_domain_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bad_domain_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bad_domain_url'] = $bad_domain_url;

        return $this;
    }

    /**
     * Gets page_rank
     *
     * @return int|null
     */
    public function getPageRank()
    {
        return $this->container['page_rank'];
    }

    /**
     * Sets page_rank
     *
     * @param int|null $page_rank page_rank
     *
     * @return self
     */
    public function setPageRank($page_rank)
    {
        if (is_null($page_rank)) {
            array_push($this->openAPINullablesSetToNull, 'page_rank');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('page_rank', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['page_rank'] = $page_rank;

        return $this;
    }

    /**
     * Gets string_guarantee
     *
     * @return string[]|null
     */
    public function getStringGuarantee()
    {
        return $this->container['string_guarantee'];
    }

    /**
     * Sets string_guarantee
     *
     * @param string[]|null $string_guarantee string_guarantee
     *
     * @return self
     */
    public function setStringGuarantee($string_guarantee)
    {
        if (is_null($string_guarantee)) {
            array_push($this->openAPINullablesSetToNull, 'string_guarantee');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('string_guarantee', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['string_guarantee'] = $string_guarantee;

        return $this;
    }

    /**
     * Gets string_guarantee_op
     *
     * @return string|null
     */
    public function getStringGuaranteeOp()
    {
        return $this->container['string_guarantee_op'];
    }

    /**
     * Sets string_guarantee_op
     *
     * @param string|null $string_guarantee_op string_guarantee_op
     *
     * @return self
     */
    public function setStringGuaranteeOp($string_guarantee_op)
    {
        if (is_null($string_guarantee_op)) {
            array_push($this->openAPINullablesSetToNull, 'string_guarantee_op');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('string_guarantee_op', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['string_guarantee_op'] = $string_guarantee_op;

        return $this;
    }

    /**
     * Gets reverse_string_guarantee
     *
     * @return string[]|null
     */
    public function getReverseStringGuarantee()
    {
        return $this->container['reverse_string_guarantee'];
    }

    /**
     * Sets reverse_string_guarantee
     *
     * @param string[]|null $reverse_string_guarantee reverse_string_guarantee
     *
     * @return self
     */
    public function setReverseStringGuarantee($reverse_string_guarantee)
    {
        if (is_null($reverse_string_guarantee)) {
            array_push($this->openAPINullablesSetToNull, 'reverse_string_guarantee');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reverse_string_guarantee', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reverse_string_guarantee'] = $reverse_string_guarantee;

        return $this;
    }

    /**
     * Gets entity_guarantee
     *
     * @return string[]|null
     */
    public function getEntityGuarantee()
    {
        return $this->container['entity_guarantee'];
    }

    /**
     * Sets entity_guarantee
     *
     * @param string[]|null $entity_guarantee entity_guarantee
     *
     * @return self
     */
    public function setEntityGuarantee($entity_guarantee)
    {
        if (is_null($entity_guarantee)) {
            array_push($this->openAPINullablesSetToNull, 'entity_guarantee');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('entity_guarantee', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['entity_guarantee'] = $entity_guarantee;

        return $this;
    }

    /**
     * Gets entity_guarantee_op
     *
     * @return string|null
     */
    public function getEntityGuaranteeOp()
    {
        return $this->container['entity_guarantee_op'];
    }

    /**
     * Sets entity_guarantee_op
     *
     * @param string|null $entity_guarantee_op entity_guarantee_op
     *
     * @return self
     */
    public function setEntityGuaranteeOp($entity_guarantee_op)
    {
        if (is_null($entity_guarantee_op)) {
            array_push($this->openAPINullablesSetToNull, 'entity_guarantee_op');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('entity_guarantee_op', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['entity_guarantee_op'] = $entity_guarantee_op;

        return $this;
    }

    /**
     * Gets countries
     *
     * @return string[]|null
     */
    public function getCountries()
    {
        return $this->container['countries'];
    }

    /**
     * Sets countries
     *
     * @param string[]|null $countries countries
     *
     * @return self
     */
    public function setCountries($countries)
    {
        if (is_null($countries)) {
            array_push($this->openAPINullablesSetToNull, 'countries');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('countries', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['countries'] = $countries;

        return $this;
    }

    /**
     * Gets countries_blacklist
     *
     * @return string[]|null
     */
    public function getCountriesBlacklist()
    {
        return $this->container['countries_blacklist'];
    }

    /**
     * Sets countries_blacklist
     *
     * @param string[]|null $countries_blacklist countries_blacklist
     *
     * @return self
     */
    public function setCountriesBlacklist($countries_blacklist)
    {
        if (is_null($countries_blacklist)) {
            array_push($this->openAPINullablesSetToNull, 'countries_blacklist');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('countries_blacklist', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['countries_blacklist'] = $countries_blacklist;

        return $this;
    }

    /**
     * Gets continents
     *
     * @return string[]|null
     */
    public function getContinents()
    {
        return $this->container['continents'];
    }

    /**
     * Sets continents
     *
     * @param string[]|null $continents continents
     *
     * @return self
     */
    public function setContinents($continents)
    {
        if (is_null($continents)) {
            array_push($this->openAPINullablesSetToNull, 'continents');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('continents', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['continents'] = $continents;

        return $this;
    }

    /**
     * Gets languages
     *
     * @return string[]|null
     */
    public function getLanguages()
    {
        return $this->container['languages'];
    }

    /**
     * Sets languages
     *
     * @param string[]|null $languages languages
     *
     * @return self
     */
    public function setLanguages($languages)
    {
        if (is_null($languages)) {
            array_push($this->openAPINullablesSetToNull, 'languages');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('languages', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['languages'] = $languages;

        return $this;
    }

    /**
     * Gets sentiment
     *
     * @return string|null
     */
    public function getSentiment()
    {
        return $this->container['sentiment'];
    }

    /**
     * Sets sentiment
     *
     * @param string|null $sentiment sentiment
     *
     * @return self
     */
    public function setSentiment($sentiment)
    {
        if (is_null($sentiment)) {
            array_push($this->openAPINullablesSetToNull, 'sentiment');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sentiment', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sentiment'] = $sentiment;

        return $this;
    }

    /**
     * Gets reporting_voice
     *
     * @return string[]|null
     */
    public function getReportingVoice()
    {
        return $this->container['reporting_voice'];
    }

    /**
     * Sets reporting_voice
     *
     * @param string[]|null $reporting_voice reporting_voice
     *
     * @return self
     */
    public function setReportingVoice($reporting_voice)
    {
        if (is_null($reporting_voice)) {
            array_push($this->openAPINullablesSetToNull, 'reporting_voice');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reporting_voice', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reporting_voice'] = $reporting_voice;

        return $this;
    }

    /**
     * Gets provocative
     *
     * @return string|null
     */
    public function getProvocative()
    {
        return $this->container['provocative'];
    }

    /**
     * Sets provocative
     *
     * @param string|null $provocative provocative
     *
     * @return self
     */
    public function setProvocative($provocative)
    {
        if (is_null($provocative)) {
            array_push($this->openAPINullablesSetToNull, 'provocative');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('provocative', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['provocative'] = $provocative;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


