<?php
/**
 * AsknewsApiSchemaV1CommonGraphRelationshipsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AskNews API
 *
 * AskNews API
 *
 * The version of the OpenAPI document: 0.22.10
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AskNews\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AsknewsApiSchemaV1CommonGraphRelationshipsTest Class Doc Comment
 *
 * @category    Class
 * @description AsknewsApiSchemaV1CommonGraphRelationships
 * @package     AskNews
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AsknewsApiSchemaV1CommonGraphRelationshipsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AsknewsApiSchemaV1CommonGraphRelationships"
     */
    public function testAsknewsApiSchemaV1CommonGraphRelationships()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nodes"
     */
    public function testPropertyNodes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "edges"
     */
    public function testPropertyEdges()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
