<?php
/**
 * WebSourceParamsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AskNews API
 *
 * AskNews API
 *
 * The version of the OpenAPI document: 0.21.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AskNews\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WebSourceParamsTest Class Doc Comment
 *
 * @category    Class
 * @description WebSourceParams
 * @package     AskNews
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WebSourceParamsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WebSourceParams"
     */
    public function testWebSourceParams()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "queries"
     */
    public function testPropertyQueries()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "domains"
     */
    public function testPropertyDomains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "strict"
     */
    public function testPropertyStrict()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lookback"
     */
    public function testPropertyLookback()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
