<?php
/**
 * AlertsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AskNews API
 *
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.28
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace AskNews\Test\Api;

use \AskNews\Configuration;
use \AskNews\ApiException;
use \AskNews\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AlertsApiTest Class Doc Comment
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AlertsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createAlert
     *
     * Create an alert.
     *
     */
    public function testCreateAlert()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAlert
     *
     * Delete an alert.
     *
     */
    public function testDeleteAlert()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAlert
     *
     * Get an alert.
     *
     */
    public function testGetAlert()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAlertLogs
     *
     * Get alert logs.
     *
     */
    public function testGetAlertLogs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAlerts
     *
     * Get all created alerts.
     *
     */
    public function testGetAlerts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAllAlertLogs
     *
     * Get all alert logs.
     *
     */
    public function testGetAllAlertLogs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putAlert
     *
     * Update an alert.
     *
     */
    public function testPutAlert()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for runAlert
     *
     * Run an existing alert.
     *
     */
    public function testRunAlert()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
