<?php
/**
 * NewsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AskNews API
 *
 * AskNews API
 *
 * The version of the OpenAPI document: 0.15.9
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace AskNews\Test\Api;

use \AskNews\Configuration;
use \AskNews\ApiException;
use \AskNews\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * NewsApiTest Class Doc Comment
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NewsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getArticle
     *
     * Get an article by its UUID.
     *
     */
    public function testGetArticle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSourcesReport
     *
     * Get the sources underlying AskNews.
     *
     */
    public function testGetSourcesReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchNews
     *
     * Search for enriched real-time news context.
     *
     */
    public function testSearchNews()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
