<?php
/**
 * NewslettersApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AskNews API
 *
 * AskNews API
 *
 * The version of the OpenAPI document: 0.23.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace AskNews\Test\Api;

use \AskNews\Configuration;
use \AskNews\ApiException;
use \AskNews\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * NewslettersApiTest Class Doc Comment
 *
 * @category Class
 * @package  AskNews
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NewslettersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteNewsletter
     *
     * Delete a newsletter.
     *
     */
    public function testDeleteNewsletter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteNewsletterContact
     *
     * Delete a newsletter contact.
     *
     */
    public function testDeleteNewsletterContact()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getNewsletter
     *
     * Get a newsletter.
     *
     */
    public function testGetNewsletter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getNewsletterContact
     *
     * Get a newsletter contact.
     *
     */
    public function testGetNewsletterContact()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getNewsletterContacts
     *
     * Get newsletter contacts.
     *
     */
    public function testGetNewsletterContacts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getNewsletters
     *
     * Get all created newsletters.
     *
     */
    public function testGetNewsletters()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPublicNewsletters
     *
     * Get all public newsletters.
     *
     */
    public function testGetPublicNewsletters()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNewsletterContact
     *
     * Update a newsletter contact.
     *
     */
    public function testPatchNewsletterContact()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postNewsletter
     *
     * Create a newsletter.
     *
     */
    public function testPostNewsletter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postNewsletterContacts
     *
     * Create a newsletter contact.
     *
     */
    public function testPostNewsletterContacts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putNewsletter
     *
     * Update a newsletter.
     *
     */
    public function testPutNewsletter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unsubscribeNewsletter
     *
     * Unsubscribe from a newsletter.
     *
     */
    public function testUnsubscribeNewsletter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
